export const mockCustomers = [
  {
    id: "CUST001",
    name: "Sarah Jenkins",
    age: 34,
    occupation: "Senior Software Engineer",
    email: "sarah.jenkins@techcorp.com",
    phone: "+1 (555) 019-2834",
    annualIncome: 135000,
    creditScore: 765,
    riskProfile: "Moderate",
    totalBalance: 68400,
    monthlySavingsRate: 25, // percentage of monthly income saved
    activeProducts: ["Checking Account", "Basic Savings", "Standard Credit Card"],
    lastContacted: "2026-05-12",
    segment: "High Value",
    notes: "Frequently pays off credit card in full. Interested in purchasing a home in the next 2 years."
  },
  {
    id: "CUST002",
    name: "David Chen",
    age: 45,
    occupation: "Medical Practice Director",
    email: "dchen@healthpartners.org",
    phone: "+1 (555) 014-9988",
    annualIncome: 245000,
    creditScore: 810,
    riskProfile: "Conservative",
    totalBalance: 312000,
    monthlySavingsRate: 35,
    activeProducts: ["Checking Account", "Premium Savings", "Auto Loan"],
    lastContacted: "2026-06-20",
    segment: "Ultra HNW",
    notes: "High net worth individual. Prefers low-risk treasury bonds but has expressed interest in wealth advisory."
  },
  {
    id: "CUST003",
    name: "Marcus Thompson",
    age: 28,
    occupation: "Freelance Graphic Designer",
    email: "marcus.creates@gmail.com",
    phone: "+1 (555) 017-4411",
    annualIncome: 55000,
    creditScore: 615,
    riskProfile: "Aggressive",
    totalBalance: 4200,
    monthlySavingsRate: 5,
    activeProducts: ["Checking Account", "Student Loan"],
    lastContacted: "2026-04-05",
    segment: "Standard",
    notes: "High debt-to-income ratio due to student loans. Irregular monthly deposits."
  },
  {
    id: "CUST004",
    name: "Elena Rostova",
    age: 41,
    occupation: "VP of Global Marketing",
    email: "elena.rostova@nexusmedia.com",
    phone: "+1 (555) 012-7744",
    annualIncome: 185000,
    creditScore: 790,
    riskProfile: "Moderate",
    totalBalance: 94000,
    monthlySavingsRate: 30,
    activeProducts: ["Checking Account", "High-Yield Savings"],
    lastContacted: "2026-06-01",
    segment: "High Value",
    notes: "Extensive international travel records in transactions. Looking for a premium travel rewards card."
  },
  {
    id: "CUST005",
    name: "Robert Miller",
    age: 52,
    occupation: "Construction Contractor",
    email: "bob.miller@millerbuilds.com",
    phone: "+1 (555) 015-3322",
    annualIncome: 95000,
    creditScore: 695,
    riskProfile: "Conservative",
    totalBalance: 52000,
    monthlySavingsRate: 15,
    activeProducts: ["Checking Account", "Business Line of Credit"],
    lastContacted: "2026-05-30",
    segment: "Standard",
    notes: "Business owner, recently enquired about equipment financing or short-term personal liquidity loan."
  },
  {
    id: "CUST006",
    name: "Aisha Rahman",
    age: 29,
    occupation: "Product Manager",
    email: "aisha.rahman@fintechhub.io",
    phone: "+1 (555) 018-8899",
    annualIncome: 110000,
    creditScore: 740,
    riskProfile: "Aggressive",
    totalBalance: 48000,
    monthlySavingsRate: 20,
    activeProducts: ["Checking Account", "Basic Savings", "Standard Credit Card"],
    lastContacted: "2026-06-15",
    segment: "High Value",
    notes: "Actively trades crypto/stocks. Interested in advanced investment options and automated portfolios."
  },
  {
    id: "CUST007",
    name: "Thomas Wright",
    age: 61,
    occupation: "Retired School Principal",
    email: "twright.education@outlook.com",
    phone: "+1 (555) 011-5566",
    annualIncome: 75000,
    creditScore: 825,
    riskProfile: "Conservative",
    totalBalance: 185000,
    monthlySavingsRate: 40,
    activeProducts: ["Checking Account", "Premium Savings", "Fixed Deposit Certificate"],
    lastContacted: "2026-04-18",
    segment: "High Value",
    notes: "Very stable pension income. Prefers offline/personalized phone support. High interest in wealth inheritance planning."
  },
  {
    id: "CUST008",
    name: "Chloe Dupont",
    age: 26,
    occupation: "Consultant",
    email: "chloe.dupont@deloitte.com",
    phone: "+1 (555) 019-3344",
    annualIncome: 88000,
    creditScore: 710,
    riskProfile: "Moderate",
    totalBalance: 19500,
    monthlySavingsRate: 12,
    activeProducts: ["Checking Account", "Basic Savings"],
    lastContacted: "2026-05-02",
    segment: "Standard",
    notes: "Frequent travel for consulting work. Pays high ATM fee charges internationally. Needs a travel-focused card."
  },
  {
    id: "CUST009",
    name: "James Anderson",
    age: 38,
    occupation: "Sales Director",
    email: "janderson@growthsolutions.com",
    phone: "+1 (555) 013-1122",
    annualIncome: 145000,
    creditScore: 720,
    riskProfile: "Moderate",
    totalBalance: 73000,
    monthlySavingsRate: 18,
    activeProducts: ["Checking Account", "Personal Loan", "Standard Credit Card"],
    lastContacted: "2026-06-25",
    segment: "High Value",
    notes: "Has an active personal loan expiring next month. High potential for personal loan refinancing or top-up."
  },
  {
    id: "CUST010",
    name: "Sofia Martinez",
    age: 31,
    occupation: "Marketing Lead",
    email: "sofia.m@creativeforce.co",
    phone: "+1 (555) 016-6655",
    annualIncome: 92000,
    creditScore: 680,
    riskProfile: "Aggressive",
    totalBalance: 29000,
    monthlySavingsRate: 15,
    activeProducts: ["Checking Account", "Basic Savings"],
    lastContacted: "2026-03-12",
    segment: "Standard",
    notes: "Regular salary deposit, balance growing. No credit card currently. Good prospect for standard or cashback card."
  },
  {
    id: "CUST011",
    name: "William Patel",
    age: 48,
    occupation: "Software Architect",
    email: "w.patel@archdesigns.org",
    phone: "+1 (555) 012-4433",
    annualIncome: 190000,
    creditScore: 785,
    riskProfile: "Moderate",
    totalBalance: 125000,
    monthlySavingsRate: 28,
    activeProducts: ["Checking Account", "Premium Savings", "Standard Credit Card"],
    lastContacted: "2026-06-11",
    segment: "High Value",
    notes: "Has large balance sitting in premium savings earning low interest. Excellent lead for investment advisory / wealth management."
  },
  {
    id: "CUST012",
    name: "Emily Taylor",
    age: 24,
    occupation: "Social Media Specialist",
    email: "emily.t@buzzagency.com",
    phone: "+1 (555) 017-9911",
    annualIncome: 48000,
    creditScore: 590,
    riskProfile: "Moderate",
    totalBalance: 3100,
    monthlySavingsRate: 3,
    activeProducts: ["Checking Account"],
    lastContacted: "2026-02-28",
    segment: "Standard",
    notes: "Multiple overdraft incidents in the last 6 months. Low savings rate."
  },
  {
    id: "CUST013",
    name: "Arthur Pendelton",
    age: 57,
    occupation: "Corporate Attorney",
    email: "apendelton@pmlaw.com",
    phone: "+1 (555) 014-2200",
    annualIncome: 280000,
    creditScore: 830,
    riskProfile: "Conservative",
    totalBalance: 450000,
    monthlySavingsRate: 45,
    activeProducts: ["Checking Account", "Premium Savings", "Home Mortgage"],
    lastContacted: "2026-06-29",
    segment: "Ultra HNW",
    notes: "High wealth category. Looking for estate planning services and customized high-yield investment options."
  },
  {
    id: "CUST014",
    name: "Grace Lee",
    age: 33,
    occupation: "UX Designer",
    email: "grace.lee@designstudio.com",
    phone: "+1 (555) 018-4422",
    annualIncome: 105000,
    creditScore: 755,
    riskProfile: "Moderate",
    totalBalance: 51000,
    monthlySavingsRate: 22,
    activeProducts: ["Checking Account", "Basic Savings", "Standard Credit Card"],
    lastContacted: "2026-05-18",
    segment: "High Value",
    notes: "Frequent flight and hotel bookings in the last 90 days. Ideal candidate for the Travel Elite Credit Card."
  },
  {
    id: "CUST015",
    name: "Daniel Kim",
    age: 42,
    occupation: "Real Estate Agent",
    email: "dkim@remaxelite.com",
    phone: "+1 (555) 016-5599",
    annualIncome: 160000,
    creditScore: 715,
    riskProfile: "Moderate",
    totalBalance: 82000,
    monthlySavingsRate: 20,
    activeProducts: ["Checking Account", "Premium Savings"],
    lastContacted: "2026-06-05",
    segment: "High Value",
    notes: "Inconsistent monthly commission deposits but high average balance. Expressed interest in personal loan for property investment."
  },
  {
    id: "CUST016",
    name: "Samantha Fox",
    age: 27,
    occupation: "HR Specialist",
    email: "samantha.f@peopledepot.org",
    phone: "+1 (555) 011-8833",
    annualIncome: 65000,
    creditScore: 640,
    riskProfile: "Conservative",
    totalBalance: 9800,
    monthlySavingsRate: 8,
    activeProducts: ["Checking Account", "Student Loan"],
    lastContacted: "2026-04-12",
    segment: "Standard",
    notes: "Strict budgeter. Pays off student loan regularly. Unlikely to take additional debt."
  },
  {
    id: "CUST017",
    name: "Oliver Harrison",
    age: 50,
    occupation: "Dentist",
    email: "dr.oliverh@harrisonteeth.com",
    phone: "+1 (555) 013-9977",
    annualIncome: 210000,
    creditScore: 795,
    riskProfile: "Moderate",
    totalBalance: 165000,
    monthlySavingsRate: 30,
    activeProducts: ["Checking Account", "Premium Savings"],
    lastContacted: "2026-06-12",
    segment: "High Value",
    notes: "No active credit cards or loans. Extremely high liquidity. Interested in expanding private dental practice. Personal loan / business loan prospect."
  },
  {
    id: "CUST018",
    name: "Isabella Rossi",
    age: 36,
    occupation: "Architect",
    email: "i.rossi@milanodesign.it",
    phone: "+1 (555) 015-7788",
    annualIncome: 120000,
    creditScore: 735,
    riskProfile: "Moderate",
    totalBalance: 42000,
    monthlySavingsRate: 15,
    activeProducts: ["Checking Account", "Basic Savings", "Standard Credit Card"],
    lastContacted: "2026-05-24",
    segment: "High Value",
    notes: "Regular business trips to Italy. Pays high foreign transaction markup fees. Premium travel card opportunity."
  },
  {
    id: "CUST019",
    name: "Lucas van der Berg",
    age: 23,
    occupation: "Graduate Research Assistant",
    email: "l.vandenberg@university.edu",
    phone: "+1 (555) 012-3300",
    annualIncome: 32000,
    creditScore: 660,
    riskProfile: "Conservative",
    totalBalance: 2400,
    monthlySavingsRate: 2,
    activeProducts: ["Checking Account"],
    lastContacted: "2026-01-15",
    segment: "Standard",
    notes: "Low cash flow. Uses bank account mostly for stipend deposits and rent payments."
  },
  {
    id: "CUST020",
    name: "Natalie Zhao",
    age: 39,
    occupation: "E-commerce Founder",
    email: "natalie@zhaoboutique.com",
    phone: "+1 (555) 014-5511",
    annualIncome: 175000,
    creditScore: 770,
    riskProfile: "Aggressive",
    totalBalance: 88000,
    monthlySavingsRate: 25,
    activeProducts: ["Checking Account", "Premium Savings", "Standard Credit Card"],
    lastContacted: "2026-06-18",
    segment: "High Value",
    notes: "Highly entrepreneurial, frequently transfers funds between personal and business checking. High travel charges."
  }
];

export const mockTransactions = [
  // CUST001 - Sarah Jenkins
  { id: "T1001", customerId: "CUST001", date: "2026-06-01", category: "Salary", amount: 7800, type: "deposit", description: "TechCorp Payroll Deposit" },
  { id: "T1002", customerId: "CUST001", date: "2026-06-05", category: "Housing", amount: -2800, type: "withdrawal", description: "Apartment Rent Payment" },
  { id: "T1003", customerId: "CUST001", date: "2026-06-12", category: "Groceries", amount: -234.50, type: "withdrawal", description: "Whole Foods Market" },
  { id: "T1004", customerId: "CUST001", date: "2026-06-18", category: "Investment", amount: -1500, type: "withdrawal", description: "Transfer to Robinhood Brokerage" },
  { id: "T1005", customerId: "CUST001", date: "2026-06-25", category: "Dining", amount: -128.40, type: "withdrawal", description: "Steakhouse Dinner" },

  // CUST002 - David Chen
  { id: "T1006", customerId: "CUST002", date: "2026-06-01", category: "Salary", amount: 15400, type: "deposit", description: "Medical Group Distribution" },
  { id: "T1007", customerId: "CUST002", date: "2026-06-04", category: "Loan", amount: -650, type: "withdrawal", description: "Auto Loan Payment" },
  { id: "T1008", customerId: "CUST002", date: "2026-06-10", category: "Utilities", amount: -420.30, type: "withdrawal", description: "Power and Gas Services" },
  { id: "T1009", customerId: "CUST002", date: "2026-06-15", category: "Investment", amount: -5000, type: "withdrawal", description: "Vanguard Mutual Funds Transfer" },
  { id: "T1010", customerId: "CUST002", date: "2026-06-28", category: "Salary", amount: 4500, type: "deposit", description: "Private Practice Consulting Fee" },

  // CUST003 - Marcus Thompson
  { id: "T1011", customerId: "CUST003", date: "2026-06-03", category: "Freelance", amount: 1800, type: "deposit", description: "Upwork Payout - Client Invoice" },
  { id: "T1012", customerId: "CUST003", date: "2026-06-07", category: "Loan", amount: -350, type: "withdrawal", description: "Sallie Mae Student Loan" },
  { id: "T1013", customerId: "CUST003", date: "2026-06-15", category: "Rent", amount: -1100, type: "withdrawal", description: "Monthly Room Rent" },
  { id: "T1014", customerId: "CUST003", date: "2026-06-22", category: "Dining", amount: -45.90, type: "withdrawal", description: "Uber Eats Dinner" },
  { id: "T1015", customerId: "CUST003", date: "2026-06-29", category: "Freelance", amount: 950, type: "deposit", description: "Logo Design Payment" },

  // CUST004 - Elena Rostova (Frequent Traveler, high value)
  { id: "T1016", customerId: "CUST004", date: "2026-06-01", category: "Salary", amount: 11200, type: "deposit", description: "Nexus Media Payroll" },
  { id: "T1017", customerId: "CUST004", date: "2026-06-03", category: "Travel", amount: -1450.80, type: "withdrawal", description: "Lufthansa Airlines Munich Ticket" },
  { id: "T1018", customerId: "CUST004", date: "2026-06-07", category: "Travel", amount: -890.00, type: "withdrawal", description: "Hilton Hotels Munich" },
  { id: "T1019", customerId: "CUST004", date: "2026-06-15", category: "Shopping", amount: -540.00, type: "withdrawal", description: "Duty Free Airport Purchase" },
  { id: "T1020", customerId: "CUST004", date: "2026-06-22", category: "Travel", amount: -980.20, type: "withdrawal", description: "Delta Air Lines JFK" },
  { id: "T1021", customerId: "CUST004", date: "2026-06-26", category: "Dining", amount: -320.00, type: "withdrawal", description: "Michelin Restaurant NYC" },

  // CUST008 - Chloe Dupont (Frequent Traveler, low balance)
  { id: "T1022", customerId: "CUST008", date: "2026-06-02", category: "Salary", amount: 5400, type: "deposit", description: "Deloitte Consulting Payroll" },
  { id: "T1023", customerId: "CUST008", date: "2026-06-06", category: "Travel", amount: -650.00, type: "withdrawal", description: "United Airlines Domestic Flight" },
  { id: "T1024", customerId: "CUST008", date: "2026-06-11", category: "Travel", amount: -220.00, type: "withdrawal", description: "Airbnb Booking Chicago" },
  { id: "T1025", customerId: "CUST008", date: "2026-06-15", category: "ATM Fee", amount: -45.00, type: "withdrawal", description: "Foreign ATM cash withdrawal fee" },

  // CUST009 - James Anderson (Active loan ending soon, wants refinance)
  { id: "T1026", customerId: "CUST009", date: "2026-06-01", category: "Salary", amount: 8200, type: "deposit", description: "Growth Solutions Salary" },
  { id: "T1027", customerId: "CUST009", date: "2026-06-05", category: "Loan", amount: -850.00, type: "withdrawal", description: "Personal Loan Payment (Term 35 of 36)" },
  { id: "T1028", customerId: "CUST009", date: "2026-06-15", category: "Housing", amount: -2100.00, type: "withdrawal", description: "Mortgage Auto-Draft" },
  { id: "T1029", customerId: "CUST009", date: "2026-06-20", category: "Automotive", amount: -320.00, type: "withdrawal", description: "Car Service Center" },

  // CUST011 - William Patel (High savings, low-interest, target for advisory)
  { id: "T1030", customerId: "CUST011", date: "2026-06-01", category: "Salary", amount: 10900, type: "deposit", description: "Enterprise Software Arch Payroll" },
  { id: "T1031", customerId: "CUST011", date: "2026-06-05", category: "Transfer", amount: 4000.00, type: "deposit", description: "Transfer from External Checking" },
  { id: "T1032", customerId: "CUST011", date: "2026-06-15", category: "Savings Interest", amount: 12.50, type: "deposit", description: "Monthly Savings Interest Credited" },
  { id: "T1033", customerId: "CUST011", date: "2026-06-20", category: "Groceries", amount: -310.40, type: "withdrawal", description: "Costco Wholesale" },

  // CUST014 - Grace Lee (Frequent Traveler, high value)
  { id: "T1034", customerId: "CUST014", date: "2026-06-01", category: "Salary", amount: 6800, type: "deposit", description: "DesignStudio UX Pay" },
  { id: "T1035", customerId: "CUST014", date: "2026-06-04", category: "Travel", amount: -950.00, type: "withdrawal", description: "British Airways LHR flight" },
  { id: "T1036", customerId: "CUST014", date: "2026-06-10", category: "Travel", amount: -720.00, type: "withdrawal", description: "Marriott Hotels London" },
  { id: "T1037", customerId: "CUST014", date: "2026-06-25", category: "Dining", amount: -150.00, type: "withdrawal", description: "London Pubs & Dining" },

  // CUST015 - Daniel Kim (Real Estate, personal loan candidate)
  { id: "T1038", customerId: "CUST015", date: "2026-06-08", category: "Commission", amount: 18500, type: "deposit", description: "Remax Escrow Deposit - Comm" },
  { id: "T1039", customerId: "CUST015", date: "2026-06-10", category: "Marketing", amount: -1500.00, type: "withdrawal", description: "Zillow Advertising Campaign" },
  { id: "T1040", customerId: "CUST015", date: "2026-06-20", category: "Office Rent", amount: -850.00, type: "withdrawal", description: "Shared Desk Space Fee" },

  // CUST017 - Oliver Harrison (Dentist, extremely high liquidity, expansion target)
  { id: "T1041", customerId: "CUST017", date: "2026-06-01", category: "Practice Revenue", amount: 22000, type: "deposit", description: "Dental Practice Merchant Settlement" },
  { id: "T1042", customerId: "CUST017", date: "2026-06-05", category: "Supplies", amount: -4500.00, type: "withdrawal", description: "Henry Schein Dental Supply" },
  { id: "T1043", customerId: "CUST017", date: "2026-06-15", category: "Staff Wages", amount: -8000.00, type: "withdrawal", description: "Hygienist & Receptionist Wages" },
  { id: "T1044", customerId: "CUST017", date: "2026-06-28", category: "Tax Deposit", amount: -3000.00, type: "withdrawal", description: "IRS Tax Estimate payment" },

  // CUST018 - Isabella Rossi (Frequent Traveler, high value)
  { id: "T1045", customerId: "CUST018", date: "2026-06-01", category: "Salary", amount: 7200, type: "deposit", description: "MilanoDesign Direct Deposit" },
  { id: "T1046", customerId: "CUST018", date: "2026-06-05", category: "Travel", amount: -1100.00, type: "withdrawal", description: "Alitalia Airlines FCO Ticket" },
  { id: "T1047", customerId: "CUST018", date: "2026-06-12", category: "Travel", amount: -650.00, type: "withdrawal", description: "Boutique Hotel Milan" },
  { id: "T1048", customerId: "CUST018", date: "2026-06-20", category: "Shopping", amount: -450.00, type: "withdrawal", description: "Milan Boutique Fashion" }
];

export const mockUsers = [
  { id: "USR001", name: "System Administrator", username: "admin", password: "password123", role: "admin", region: "All Regions", email: "admin@observebank.com", phone: "+1 (555) 010-0000", portfolioSize: "₹0.00", conversionRate: "0.0%" },
  { id: "USR002", name: "Sarah Connor", username: "sarah", password: "password123", role: "rm", region: "Northeast Region (NYC Head Office)", email: "sconnor@observebank.com", phone: "+1 (555) 012-9981", portfolioSize: "₹4.25M", conversionRate: "82.4%" }
];
